# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  # vmImage: 'Ubuntu-16.04'
  vmImage: 'vs2017-win2016'

variables:
  buildConfiguration: 'Release'
  projectName: 'Complexity'
  framework: netcoreapp2.2


steps:
- script: dotnet restore $(projectName)
- script: dotnet build $(projectName) --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: build
    projects: '$(projectName)/**/*.csproj'
    arguments: '--configuration Release' # Update this to match your need

- task: DotNetCoreCLI@2
  inputs:
    command: test
    projects: '$(projectName)/Tests/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

- script: dotnet test $(projectName)/Tests --logger trx
- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'

- task: DotNetCoreCLI@2
  inputs:
    command: publish
    publishWebProjects: True
    arguments: '$(projectName) --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: True